# Generated by Django 4.1.7 on 2023-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_customer',
            name='Message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info_customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='info_customer',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
