# Generated by Django 4.1.7 on 2023-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_info_customer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_customer',
            name='Message',
            field=models.CharField(max_length=50),
        ),
    ]
