# Generated by Django 4.1.7 on 2023-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_info_customer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_customer',
            name='Message',
            field=models.CharField(default='', max_length=25),
        ),
    ]
