# Generated by Django 4.1.7 on 2023-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_info_customer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_customer',
            name='Message',
            field=models.TextField(null=True),
        ),
    ]
