# Generated by Django 4.1.7 on 2023-11-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_info_customer_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_customer',
            old_name='Message',
            new_name='message',
        ),
    ]
